version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app